name: Create Archive
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        filename: 'VIAME-JoBBS-Models.zip'
        path: packages/VIAME-JoBBS-Models/

    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
          artifacts: "VIAME-JoBBS-Models.zip"
          token: ${{ secrets.GIT_TOKEN }}
          tag: latest
          allowUpdates: true
