name: Create Archive
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        lfs: true
          
    - run: git lfs pull

    - name: Easy Zip Files
      uses: vimtor/action-zip@v1
      with:
        dest: VIAME-JoBBS-Models.zip
        files: packages/VIAME-JoBBS-Models/

    - name: Delete artifacts
      uses: geekyeggo/delete-artifact@v1
      with:
          name: |
            latest.zip
            latest.tar.gz
    
    # Files or directories to zip
    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
          artifacts: "VIAME-JoBBS-Models.zip"
          token: ${{ secrets.GIT_TOKEN }}
          tag: latest
          allowUpdates: true
